### ISSUE TITLE
Build broken on Windows by #112

### ISSUE THREAD

**Issue by tgeoghegan** [rustls/rustls-ffi#119]
When I build now, I get:
```
   Compiling rustls v0.19.1=======>      ] 19/24: sct, webpki, ring
error[E0432]: unresolved imports `crate::io::rustls_write_vectored_callback`, `crate::io::VectoredCallbackWriter`, `crat
e::io::VectoredWriteCallback`
 --> src\connection.rs:8:5
  |
8 |     rustls_write_vectored_callback, CallbackReader, CallbackWriter, ReadCallback,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     |
  |     no `rustls_write_vectored_callback` in `io`
  |     help: a similar name exists in the module: `rustls_write_callback`
9 |     VectoredCallbackWriter, VectoredWriteCallback, WriteCallback,
  |     ^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^ no `VectoredWriteCallback` in `io`
  |     |
  |     no `VectoredCallbackWriter` in `io`
```
What!?

_Originally posted by @gvanem in https://github.com/rustls/rustls-ffi/issues/112#issuecomment-868299417_

**Comment by tgeoghegan** [comment]
Based on gvanem's previously filed issues, I'm guessing this is on Windows, and it's because `rustls_write_vectored_callback` is `#[cfg(unix)]`. The other problem is that our CI doesn't build or test on Windows, which we might consider fixing in this issue if it's a matter of adding it to [the matrix](https://github.com/rustls/rustls-ffi/blob/4880b5cc11d16a158836a302f38435005c28c276/.github/workflows/test.yaml#L11).

@gvanem could you please confirm whether you encountered this problem on Wiindows, along with any other reproduction steps?

**Comment by gvanem** [comment]
@tgeoghegan Yes. On Windows. But if I remove those `[cfg(unix)]`, it compiles. But yet to try if it works.

**Comment by jsha** [comment]
Ah, good point. Removing the `#[cfg(unix)]` should work. I'm realizing now I added those guards in an earlier version where I was depending directly on the `sys/uio.h` `iovec` type. Since we're not depending on those now, I think simply removing the `#[cfg(unix)]` guards should be fine. If you're not using the vectored I/O features you won't see any functionality difference.

If you _are_ interested in using the vectored I/O features: It should be possible to cast rustls_iovec to WSABUF, per the IoSlice documentation: https://doc.rust-lang.org/nightly/std/io/struct.IoSlice.html. I haven't tried it out though.

**Comment by tgeoghegan** [comment]
Yeah, we speculated that it might Just Work on Windows since `std::io::IoSlice` is designed to be compatible with both `struct iovec/writev(2)` and `WSABUF/wsasend`. It certainly seems easier than putting in more `#[cfg(unix)]`. I'm going to pursue that and will also try adding Windows to our CI build and test matrix, though I may throw in the towel if the best way to do that is something like CMake. Which is not to say I'm against CMake but I want to keep the response to this problem focused on unbreaking the Windows build.
